language: php

sudo: false

notifications:
  email:
    on_success: never

php:
  - 5.6.9
  - 7.1
  - 7.2
  - 7.3

install:
  -
  - composer require --dev php-coveralls/php-coveralls

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n
  - if [[ $(phpenv version-name) == '5.6.9' ]]; then composer require --dev phpunit/phpunit ^5 -n ; fi
  - if [[ $(phpenv version-name) == '7.1' ]]; then composer require --dev phpunit/phpunit ^7 -n ; fi
  - if [[ $(phpenv version-name) == '7.2' ]]; then composer require --dev phpunit/phpunit ^8 -n ; fi
  - if [[ $(phpenv version-name) == '7.3' ]]; then composer require --dev phpunit/phpunit ^8 -n ; fi

script:
  - mkdir -p build/logs
  - if [[ $(phpenv version-name) == '5.6.9' ]]; then vendor/bin/phpunit --bootstrap vendor/autoload.php tests/UnitTest/tests.php --coverage-clover build/logs/clover.xml
  - if [[ $(phpenv version-name) == '7.1' ]]; then vendor/bin/phpunit --bootstrap vendor/autoload.php tests/UnitTest/tests.php --coverage-clover build/logs/clover.xml ; fi
  - if [[ $(phpenv version-name) == '7.2' ]]; then phpunit --bootstrap vendor/autoload.php tests/UnitTest/tests.php --coverage-clover build/logs/clover.xml ; fi
  - if [[ $(phpenv version-name) == '7.3' ]]; then phpunit --bootstrap vendor/autoload.php tests/UnitTest/tests.php --coverage-clover build/logs/clover.xml ; fi

after_success:
  - travis_retry php vendor/bin/php-coveralls