language: php

sudo: false

notifications:
  email:
    on_success: never

php:
  - 7.1
  - 7.2

install:
  -
  - composer require --dev php-coveralls/php-coveralls

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n
  - if [[ $(phpenv version-name) == '7.1' ]]; then composer require --dev phpunit/phpunit ^7 -n ; fi
  - if [[ $(phpenv version-name) == '7.2' ]]; then composer require --dev phpunit/phpunit ^8 -n ; fi

script:
  - mkdir -p build/logs
  - phpunit --bootstrap vendor/autoload.php tests/UnitTest/tests.php --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls