language: php

sudo: false

notifications:
  email:
    on_success: never

php:
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n
  - composer require --dev php-coveralls/php-coveralls
  - if [[ $(phpenv version-name) == '8.0' ]]; then composer require --dev phpunit/phpunit ^9.5 -n ; fi

script:
  - mkdir -p build/logs
  - if [[ $(phpenv version-name) == '8.0' ]]; then phpunit --bootstrap vendor/autoload.php tests/UnitTest/tests.php --coverage-clover build/logs/clover.xml ; fi

after_success:
  - travis_retry php vendor/bin/php-coveralls
